name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron:  '0 6 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: ["v1.9.x"]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denolib/setup-deno@v2.3.0
        with:
          deno-version: ${{ matrix.deno }}

      - name: Deno Version
        run: deno --version

      - name: Cache Dependencies
        run: deno cache deps_test.ts

      - name: Run Tests
        run: deno test
